package conver

var slot = map[string]string{
	"flower":  "flower",
	"feather": "plume",
	"sand":    "eon",
	"cup":     "goblet",
	"head":    "circlet",
}

var subStat = map[string]string{
	"critical":         "critRate",
	"criticalDamage":   "critDamage",
	"attackStatic":     "flatATK",
	"attackPercentage": "percentATK",
	"elementalMastery": "elementalMastery",
	"recharge":         "energyRecharge",
	"lifeStatic":       "flatHP",
	"lifePercentage":   "percentHP",
	"defendStatic":     "flatDEF",
	"defendPercentage": "percentDEF",
	"physicalBonus":    "physicalDamage",
	"cureEffect":       "healing",
	"rockBonus":        "geoDamage",
	"windBonus":        "anemoDamage",
	"iceBonus":         "cryoDamage",
	"waterBonus":       "hydroDamage",
	"fireBonus":        "pyroDamage",
	"thunderBonus":     "electroDamage",
}

var setName = map[string]string{
	"archaicPetra":           "archaic_petra",
	"blizzardStrayer":        "blizzard_walker",
	"bloodstainedChivalry":   "bloodstained_chivalry",
	"crimsonWitch":           "crimson_witch_of_flames",
	"gladiatorFinale":        "gladiators_finale",
	"heartOfDepth":           "heart_of_depth",
	"lavaWalker":             "lavawalker",
	"maidenBeloved":          "maiden_beloved",
	"noblesseOblige":         "noblesse_oblige",
	"retracingBolide":        "retracing_bolide",
	"thunderSmoother":        "thundersoother",
	"thunderingFury":         "thundering_fury",
	"viridescentVenerer":     "viridescent_venerer",
	"wandererTroupe":         "wanderers_troupe",
	"berserker":              "berserker",
	"braveHeart":             "brave_heart",
	"defenderWill":           "defenders_will",
	"exile":                  "the_exile",
	"gambler":                "gambler",
	"instructor":             "instructor",
	"martialArtist":          "martial_artist",
	"prayersForDestiny":      "prayers_for_destiny",
	"prayersForIllumination": "prayers_for_illumination",
	"prayersForWisdom":       "prayers_for_wisdom",
	"prayersToSpringtime":    "prayers_to_springtime",
	"resolutionOfSojourner":  "resolution_of_sojourner",
	"scholar":                "scholar",
	"tinyMiracle":            "tiny_miracle",
	"adventurer":             "adventurer",
	"luckyDog":               "lucky_dog",
	"travelingDoctor":        "traveling_doctor",
	"tenacityOfTheMillelith": "tenacity_of_the_millelith",
	"paleFlame":              "pale_flame",
	"emblemOfSeveredFate":    "seal_of_insulation",
	"shimenawaReminiscence":  "reminiscence_of_shime",
}
